### ISSUE TITLE
Trouble using ifmO3r logger code

### ISSUE THREAD

**Issue by niallomahony93** [ifm/ifm3d#345]
Hi, 

I am following the tutorial on https://ifm3d.com/logging2.html using the ifm03r pip module.

This is the code;
```python
import ifmO3r


import os
from ifmO3r.ifm3dTiny import Device, FrameGrabber, ImageBuffer, ImageLogger


IP = "192.168.0.69"
PORT = 50012

cam = Device(IP, PORT)
fg = FrameGrabber(cam)
im = ImageBuffer()
print("ok1")
cwd = os.getcwd()
data_path = os.path.join(cwd, 'data')

imgLogger = ImageLogger(cam, fg, im, data_path)

imgLogger.get_current_frame()
save_this = {
    "distance": "distance_frame1", 
    "amplitude": "amplitude_frame1", 
    "confidence": "confidence_frame1", 
    "x": "x_frame1", 
    "y": "y_frame1", 
    "z": "z_frame1",
    }
imgLogger.write_to_h5(save_this)
imgLogger.write_binary(save_this)
save_imgs = {
    "distance": "distance_frame1", 
    "amplitude": "amplitude_frame1", 
    "confidence": "confidence_frame1",
    }
imgLogger.write_png(save_imgs)

imgLogger.save_frame_as_pickle('frame1')
imgLogger.load_frame_from_pickle('data/frame1.p')
```
When I use the logger module I get this error:

```
> Traceback (most recent call last):
  File "examples/o3r/viewer/ifm3dpy_logger.py", line 42, in <module>
    imgLogger.write_to_h5(save_this)
  File "/home/niall/anaconda3/envs/my_env/lib/python3.7/site-packages/ifmO3r/ifm3dTiny/logger.py", line 188, in write_to_h5
    confidence_img = self.imageBuffer.confidence_image()
  File "/home/niall/anaconda3/envs/my_env/lib/python3.7/site-packages/ifmO3r/ifm3dTiny/grabber.py", line 433, in confidence_image
    self.frame["image_width"]),
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/niall/anaconda3/envs/my_env/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/niall/anaconda3/envs/my_env/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 77056 into shape (172,224)
```

It is like the camera is returning an array twice the size the logger is expecting. (77056 = 172*224*2) This is my camera config;

```
> "device": {
        "clock": {
            "currentTime": 1581091943025593920
        },
        "diagnostic": {
            "temperatures": [],
            "upTime": 1299000000000
        },
        "info": {
            "device": "0301",
            "deviceTreeBinaryBlob": "tegra186-quill-p3310-1000-c03-00-base.dtb",
            "features": {},
            "name": "great_o3r",
            "partNumber": "M03975",
            "productionState": "AA",
            "serialNumber": "000201234179",
            "vendor": "0001"
        },
        "network": {
            "authorized_keys": "",
            "ipAddressConfig": 0,
            "macEth0": "00:04:4B:EA:9F:83",
            "macEth1": "00:02:01:23:41:79",
            "networkSpeed": 1000,
            "staticIPv4Address": "192.168.0.69",
            "staticIPv4Gateway": "192.168.0.201",
            "staticIPv4SubNetMask": "255.255.255.0",
            "useDHCP": False
        },
        "state": {
            "errorMessage": "",
            "errorNumber": ""
        },
        "swVersion": {
            "kernel": "4.9.140-l4t-r32.4+gc35f5eb9d1d9",
            "l4t": "r32.4.3",
            "os": "0.13.13-221",
            "schema": "v0.1.0",
            "swu": "0.15.12"
        }
    },
    "ports": {
        "port0": {
            "acquisition": {
                "framerate": 10.0,
                "version": {
                    "major": 0,
                    "minor": 0,
                    "patch": 0
                }
            },
            "data": {
                "algoDebugConfig": {},
                "availablePCICOutput": [],
                "pcicTCPPort": 50010
            },
            "info": {
                "device": "2301",
                "deviceTreeBinaryBlobOverlay": "001-ov9782.dtbo",
                "features": {
                    "fov": {
                        "horizontal": 127,
                        "vertical": 80
                    },
                    "resolution": {
                        "height": 800,
                        "width": 1280
                    },
                    "type": "2D"
                },
                "name": "",
                "partNumber": "M03933",
                "productionState": "AA",
                "sensor": "OV9782",
                "sensorID": "OV9782_127x80_noIllu_Csample",
                "serialNumber": "000000000435",
                "vendor": "0001"
            },
            "mode": "experimental_autoexposure2D",
            "processing": {
                "extrinsicHeadToUser": {
                    "rotX": 0.0,
                    "rotY": 0.0,
                    "rotZ": 0.0,
                    "transX": 0.0,
                    "transY": 0.0,
                    "transZ": 0.0
                },
                "version": {
                    "major": 0,
                    "minor": 0,
                    "patch": 0
                }
            },
            "state": "RUN"
        },
        "port1": {
            "acquisition": {
                "framerate": 10.0,
                "version": {
                    "major": 0,
                    "minor": 0,
                    "patch": 0
                }
            },
            "data": {
                "algoDebugConfig": {},
                "availablePCICOutput": [],
                "pcicTCPPort": 50011
            },
            "info": {
                "device": "2301",
                "deviceTreeBinaryBlobOverlay": "001-ov9782.dtbo",
                "features": {
                    "fov": {
                        "horizontal": 127,
                        "vertical": 80
                    },
                    "resolution": {
                        "height": 800,
                        "width": 1280
                    },
                    "type": "2D"
                },
                "name": "",
                "partNumber": "M03933",
                "productionState": "AA",
                "sensor": "OV9782",
                "sensorID": "OV9782_127x80_noIllu_Csample",
                "serialNumber": "000000000433",
                "vendor": "0001"
            },
            "mode": "experimental_autoexposure2D",
            "processing": {
                "extrinsicHeadToUser": {
                    "rotX": 0.0,
                    "rotY": 0.0,
                    "rotZ": 0.0,
                    "transX": 0.0,
                    "transY": 0.0,
                    "transZ": 0.0
                },
                "version": {
                    "major": 0,
                    "minor": 0,
                    "patch": 0
                }
            },
            "state": "RUN"
        },
        "port2": {
            "acquisition": {
                "exposureLong": 5000,
                "exposureShort": 400,
                "framerate": 10.0,
                "offset": 0.0,
                "version": {
                    "major": 0,
                    "minor": 0,
                    "patch": 0
                }
            },
            "data": {
                "algoDebugConfig": {},
                "availablePCICOutput": [],
                "pcicTCPPort": 50012
            },
            "info": {
                "device": "3101",
                "deviceTreeBinaryBlobOverlay": "001-irs2381c.dtbo",
                "features": {
                    "fov": {
                        "horizontal": 60,
                        "vertical": 45
                    },
                    "resolution": {
                        "height": 172,
                        "width": 224
                    },
                    "type": "3D"
                },
                "name": "",
                "partNumber": "M03933",
                "productionState": "AA",
                "sensor": "IRS2381C",
                "sensorID": "IRS2381C_60x45_4x2W_60x45_C2",
                "serialNumber": "000000000435",
                "vendor": "0001"
            },
            "mode": "standard_range2m",
            "processing": {
                "diParam": {
                    "anfFilterSizeDiv2": 2,
                    "enableDynamicSymmetry": True,
                    "enableStraylight": True,
                    "enableTemporalFilter": True,
                    "excessiveCorrectionThreshAmp": 0.3,
                    "excessiveCorrectionThreshDist": 0.08,
                    "maxDistNoise": 0.02,
                    "maxSymmetry": 0.4,
                    "medianSizeDiv2": 0,
                    "minAmplitude": 20.0,
                    "minReflectivity": 0.0,
                    "mixedPixelFilterMode": 1,
                    "mixedPixelThresholdRad": 0.15
                },
                "extrinsicHeadToUser": {
                    "rotX": 0.0,
                    "rotY": 0.0,
                    "rotZ": 0.0,
                    "transX": 0.0,
                    "transY": 0.0,
                    "transZ": 0.0
                },
                "version": {
                    "major": 0,
                    "minor": 0,
                    "patch": 0
                }
            },
            "state": "RUN"
        },
        "port3": {
            "acquisition": {
                "exposureLong": 5000,
                "exposureShort": 400,
                "framerate": 20.0,
                "offset": 0.0,
                "version": {
                    "major": 0,
                    "minor": 0,
                    "patch": 0
                }
            },
            "data": {
                "algoDebugConfig": {},
                "availablePCICOutput": [],
                "pcicTCPPort": 50013
            },
            "info": {
                "device": "3101",
                "deviceTreeBinaryBlobOverlay": "001-irs2381c.dtbo",
                "features": {
                    "fov": {
                        "horizontal": 60,
                        "vertical": 45
                    },
                    "resolution": {
                        "height": 172,
                        "width": 224
                    },
                    "type": "3D"
                },
                "name": "",
                "partNumber": "M03933",
                "productionState": "AA",
                "sensor": "IRS2381C",
                "sensorID": "IRS2381C_60x45_4x2W_60x45_C2",
                "serialNumber": "000000000433",
                "vendor": "0001"
            },
            "mode": "standard_range2m",
            "processing": {
                "diParam": {
                    "anfFilterSizeDiv2": 2,
                    "enableDynamicSymmetry": True,
                    "enableStraylight": True,
                    "enableTemporalFilter": False,
                    "excessiveCorrectionThreshAmp": 0.3,
                    "excessiveCorrectionThreshDist": 0.08,
                    "maxDistNoise": 0.02,
                    "maxSymmetry": 0.4,
                    "medianSizeDiv2": 0,
                    "minAmplitude": 20.0,
                    "minReflectivity": 0.0,
                    "mixedPixelFilterMode": 1,
                    "mixedPixelThresholdRad": 0.15
                },
                "extrinsicHeadToUser": {
                    "rotX": 0.0,
                    "rotY": 0.0,
                    "rotZ": 0.0,
                    "transX": 0.0,
                    "transY": 0.0,
                    "transZ": 0.0
                },
                "version": {
                    "major": 0,
                    "minor": 0,
                    "patch": 0
                }
            },
            "state": "RUN"
        }
    }
}
)
```

**Comment by desengph** [comment]
Hi @niallomahony93 

The software code which you're referring to is “legacy code”. The Python package ifmo3r is unfortunately no longer supported.

Since the latest firmware releases the interface has changed, the effect is what you're seeing here. Part of this change has been the definition of the confidence image, which is now 16bit per pixel value instead of 8 bit.

We would like to suggest that you switch to our latest Python package – you can find it [here](https://pypi.org/project/ifm3dpy/).

For a more detailed description about the software features and the definition of all images, please follow these links.
[How to use the ifm3dpy library](http://ifm3d.com/sphinx-doc/build/html/ifm3d/doc/sphinx/content/examples/o3r/index.html)
[O3R images and filter: how to get started with your O3R](http://ifm3d.com/sphinx-doc/build/html/documentation/O3R/README.html) 

If you have any questions about the ifm3dpy or the O3R, please let us know.

**Comment by j-friedl** [comment]
@desengph wrote:
> For a more detailed description about the software features and the definition of all images, please follow these links. [How to use the ifm3dpy library](http://ifm3d.com/sphinx-doc/build/html/ifm3d/doc/sphinx/content/examples/o3r/index.html)
However, there's no page ;)

**Comment by lola-masson** [comment]
I am guessing this document has moved since the comment you mentioned. All the documentation is on [this](https://ifm3d.com/sphinx-doc/build/html/index.html) website.
